# -*- coding: utf-8 -*-
"""DS_project2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W6pK1dWuciU-BPmT-ardQrOBLzKsFH5u
"""

import pandas as pd

# Loading data
synergy_df = pd.read_csv("synergy_logistics_database.csv", index_col="register_id")
synergy_df

"""## 10 rutas más demandadas"""

synergy_df["route"] = synergy_df["origin"] + "-" + synergy_df["destination"]
route_df = synergy_df[["route", "total_value"]]
route_value_df = (route_df.groupby("route")
.sum()
.sort_values(by="total_value", ascending=False)
.iloc[:20])
route_value_df

route_count_df = route_df["route"].value_counts().iloc[:10].to_frame()
route_count_df

pd.merge(route_count_df, route_value_df, how="left", left_index=True, right_index=True)

"""Las rutas mas solicitadas son las que se muestran en la tabla anterior, en la segunda columna se encuentran los ingresos que ha recibido la ruta y si existe el valor, significa que es una ruta que se encuentra entre las 20 que más ganancias genera y se deberían de centrar en ellas.

# Medio de transporte utilizado. 

## ¿Cuáles son los __3 medios de transporte más importantes__ para Synergy logistics considerando el valor de las importaciones y exportaciones?
"""

transport_mode_df = synergy_df.groupby("transport_mode")
(transport_mode_df["total_value"]
.sum()
.sort_values(ascending=False)
.iloc[:4])

"""## ¿Cuál es medio de transporte que podrían reducir?

# Valor total de importaciones y exportaciones.

## Países que le generan el 80% del valor de las exportaciones e importaciones
"""

origin_df = synergy_df.groupby("origin")["total_value"].sum().to_frame()
origin_df

destination_df = synergy_df.groupby("destination")["total_value"].sum().to_frame()
destination_df

country_df = (pd.merge(origin_df, destination_df,
                      right_index=True, left_index=True, how="outer")
                      .fillna(0))
country_df

country_df["total"] = country_df["total_value_x"] + country_df["total_value_y"]
country_revenue_df = country_df.sort_values(by="total", ascending=False)["total"]
total_revenue = country_revenue_df.sum()
total_revenue*0.8

x, i = 0, 0
for c in country_revenue_df:
    if x >= total_revenue*0.8:
        print(x)
        break
    x += c
    i += 1
print(i)

"""Los países en los que se deberían de centrar son los que generan 80% de las ganancias, los cuales son:"""

country_revenue_df.iloc[:i]

!apt-get install texlive texlive-xetex texlive-latex-extra pandoc
!pip install pypandoc

from google.colab import drive
drive.mount('/content/drive')

!jupyter nbconvert --to latex "/content/drive/MyDrive/Colab Notebooks/DS_project2.ipynb"